/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Color;

/**
 *
 * @author Charles
 */
public class formMensagem extends javax.swing.JFrame {

    /**
     * Creates new form formMensagem
     */
    
    private void mudarCor(int i){
        //JOptionPane.showMessageDialog(null, this.getContentPane().getForeground().toString());
        //51,51,51
        
        //255, 221, 204
        
        if(i == 0){//preto
            float[] c = Color.RGBtoHSB(0, 0, 0, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.WHITE);
        }
        else if(i == 1){ //Original
            float[] c = Color.RGBtoHSB(240, 240, 240, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.BLACK);
        }
        else if(i == 2){//laranja
            float[] c = Color.RGBtoHSB(255, 221, 204, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.BLACK);
        }
        else if(i == 3){ ///amarelo
            float[] c = Color.RGBtoHSB(255, 255, 179, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.BLACK);
        }
        else if(i == 4){ //Azul
            float[] c = Color.RGBtoHSB(128, 223, 255, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));

            jLabel1.setForeground(Color.BLACK);
        }
    }
    
    public formMensagem(String m, int z) {
        initComponents();
        mudarCor(z);
        jLabel1.setText(m);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAG");
        setResizable(false);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
