/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import java.awt.Color;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author Charles
 */
public class formCreditos extends javax.swing.JFrame {

    /**
     * Creates new form formCreditos
     */
    public formCreditos(int i) {
        initComponents();
        mudarCor(i);
    }

    private void mudarCor(int i){
        //JOptionPane.showMessageDialog(null, this.getContentPane().getForeground().toString());
        //51,51,51
        
        //255, 221, 204
        
        if(i == 0){//preto
            float[] c = Color.RGBtoHSB(0, 0, 0, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.WHITE);
            jLabel2.setForeground(Color.WHITE);
        }
        else if(i == 1){ //Original
            float[] c = Color.RGBtoHSB(240, 240, 240, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
        }
        else if(i == 2){//laranja
            float[] c = Color.RGBtoHSB(255, 221, 204, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
        }
        else if(i == 3){ ///amarelo
            float[] c = Color.RGBtoHSB(255, 255, 179, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
        }
        else if(i == 4){ //Azul
            float[] c = Color.RGBtoHSB(128, 223, 255, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAG");
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setText("<html> <strong> Simulador do Algoritmo de Cristian </strong> </html>");

        jLabel2.setText("<html> Desenvolvido em <strong> Java </strong> (Dá para perceber pelo ícone) Por <strong> Charles Samuel Costa Duarte </strong> com base o código do <a href='https://github.com/FilipeNavas/AlgoritmoDeCristian'>GitHub</a> <button> </button> </html>");
        jLabel2.setToolTipText("https://github.com/FilipeNavas/AlgoritmoDeCristian");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        //System.out.println(evt.getX());
        //System.out.println(evt.getY());
        if(evt.getX() >= 20 && evt.getX() <= 54 && evt.getY() >= 54 && evt.getY() <= 69){
            try {
                Desktop.getDesktop().browse(new URI("https://github.com/FilipeNavas/AlgoritmoDeCristian"));
            } catch (URISyntaxException | IOException ex) {
                //It looks like there's a problem
                System.out.println(ex.getMessage());
            }
        }
        /*try {
            Desktop.getDesktop().browse(new URI("https://github.com/FilipeNavas/AlgoritmoDeCristian"));
        } catch (URISyntaxException | IOException ex) {
            //It looks like there's a problem
            System.out.println(ex.getMessage());
        }*/
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
