/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import static formulario.formXX.f;
import java.awt.Color;


/**
 *
 * @author Charles
 */
public class formOpções extends javax.swing.JFrame{

    /**
     * Creates new form formOpções
     * @param i Valor inteiro da cor
     * @param v Valor boolean para salvar
     */
    public formOpções(int i, boolean v) {
        initComponents();
        
        ckSave.setSelected(v);
        
        mudarCor(i);
        //f.setForeground(Color.white);
    }

    private void mudarCor(int i){
        //JOptionPane.showMessageDialog(null, this.getContentPane().getForeground().toString());
        //51,51,51
        
        //255, 221, 204
        
        if(i == 0){//preto
            float[] c = Color.RGBtoHSB(0, 0, 0, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jrPr.setSelected(true);
            
            
            jrAm.setForeground(Color.WHITE);
            jrAz.setForeground(Color.WHITE);
            jrLa.setForeground(Color.WHITE);
            jrOr.setForeground(Color.WHITE);
            jrPr.setForeground(Color.WHITE);
            jLabel1.setForeground(Color.WHITE);
            jLabel2.setForeground(Color.WHITE);
            ckSave.setForeground(Color.WHITE);
        }
        else if(i == 1){ //Original
            float[] c = Color.RGBtoHSB(240, 240, 240, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jrOr.setSelected(true);
            
            jrAm.setForeground(Color.BLACK);
            jrAz.setForeground(Color.BLACK);
            jrLa.setForeground(Color.BLACK);
            jrOr.setForeground(Color.BLACK);
            jrPr.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            ckSave.setForeground(Color.BLACK);
        }
        else if(i == 2){//laranja
            float[] c = Color.RGBtoHSB(255, 221, 204, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jrLa.setSelected(true);
            
            jrAm.setForeground(Color.BLACK);
            jrAz.setForeground(Color.BLACK);
            jrLa.setForeground(Color.BLACK);
            jrOr.setForeground(Color.BLACK);
            jrPr.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            ckSave.setForeground(Color.BLACK);
        }
        else if(i == 3){ ///amarelo
            float[] c = Color.RGBtoHSB(255, 255, 179, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jrAm.setSelected(true);
            
            jrAm.setForeground(Color.BLACK);
            jrAz.setForeground(Color.BLACK);
            jrLa.setForeground(Color.BLACK);
            jrOr.setForeground(Color.BLACK);
            jrPr.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            ckSave.setForeground(Color.BLACK);
        }
        else if(i == 4){ //Azul
            float[] c = Color.RGBtoHSB(128, 223, 255, null);
            this.getContentPane().setBackground(Color.getHSBColor(c[0], c[1], c[2]));
            
            jrAz.setSelected(true);
            
            jrAm.setForeground(Color.BLACK);
            jrAz.setForeground(Color.BLACK);
            jrLa.setForeground(Color.BLACK);
            jrOr.setForeground(Color.BLACK);
            jrPr.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            ckSave.setForeground(Color.BLACK);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jrLa = new javax.swing.JRadioButton();
        jrPr = new javax.swing.JRadioButton();
        jrOr = new javax.swing.JRadioButton();
        jrAz = new javax.swing.JRadioButton();
        jrAm = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ckSave = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SAG");
        setLocationByPlatform(true);
        setResizable(false);

        jrLa.setText("Laranja");
        jrLa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrLaActionPerformed(evt);
            }
        });

        jrPr.setText("Preto");
        jrPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrPrActionPerformed(evt);
            }
        });

        jrOr.setText("Original");
        jrOr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrOrActionPerformed(evt);
            }
        });

        jrAz.setText("Azul");
        jrAz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAzActionPerformed(evt);
            }
        });

        jrAm.setText("Amarelo");
        jrAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrAmActionPerformed(evt);
            }
        });

        jLabel1.setText("Mudar Cor");

        jLabel2.setText("Salvar Log");

        ckSave.setLabel("Sim");
        ckSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(ckSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrAm)
                    .addComponent(jrAz)
                    .addComponent(jrOr)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrPr)
                            .addComponent(jrLa))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrLa)
                    .addComponent(ckSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrPr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrOr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrAz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrAm)
                .addGap(82, 82, 82))
        );

        jrLa.getAccessibleContext().setAccessibleName("");
        jrPr.getAccessibleContext().setAccessibleName("");
        jrOr.getAccessibleContext().setAccessibleName("");
        jrAz.getAccessibleContext().setAccessibleName("");
        jrAm.getAccessibleContext().setAccessibleName("");
        jrAm.getAccessibleContext().setAccessibleDescription("");
        jLabel1.getAccessibleContext().setAccessibleName("");
        ckSave.getAccessibleContext().setAccessibleName("");
        ckSave.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrLaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrLaActionPerformed
        // TODO add your handling code here:
        jrAm.setSelected(false);
        jrAz.setSelected(false);
        jrOr.setSelected(false);
        jrPr.setSelected(false);
        f.mudarCor(2);
        f.setN(2);
        this.mudarCor(2);
    }//GEN-LAST:event_jrLaActionPerformed

    private void jrPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrPrActionPerformed
        // TODO add your handling code here:
        jrAm.setSelected(false);
        jrAz.setSelected(false);
        jrOr.setSelected(false);
        jrLa.setSelected(false);
        f.mudarCor(0);
        f.setN(0);
        this.mudarCor(0);
    }//GEN-LAST:event_jrPrActionPerformed

    private void jrOrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrOrActionPerformed
        // TODO add your handling code here:
        jrAm.setSelected(false);
        jrAz.setSelected(false);
        jrLa.setSelected(false);
        jrPr.setSelected(false);
        f.mudarCor(1);
        f.setN(1);
        this.mudarCor(1);
    }//GEN-LAST:event_jrOrActionPerformed

    private void jrAzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAzActionPerformed
        // TODO add your handling code here:
        jrAm.setSelected(false);
        jrLa.setSelected(false);
        jrOr.setSelected(false);
        jrPr.setSelected(false);
        f.mudarCor(4);
        f.setN(4);
        this.mudarCor(4);
    }//GEN-LAST:event_jrAzActionPerformed

    private void jrAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrAmActionPerformed
        // TODO add your handling code here:
        jrLa.setSelected(false);
        jrAz.setSelected(false);
        jrOr.setSelected(false);
        jrPr.setSelected(false);
        f.mudarCor(3);
        f.setN(3);
        this.mudarCor(3);
    }//GEN-LAST:event_jrAmActionPerformed

    private void ckSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckSaveActionPerformed
        // TODO add your handling code here:
        if(ckSave.isSelected()){
            f.setSave(true);
        }
        else{
            f.setSave(false);
        }
    }//GEN-LAST:event_ckSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jrAm;
    private javax.swing.JRadioButton jrAz;
    private javax.swing.JRadioButton jrLa;
    private javax.swing.JRadioButton jrOr;
    private javax.swing.JRadioButton jrPr;
    // End of variables declaration//GEN-END:variables
}
